apiVersion: v1
kind: PersistentVolume
metadata:
  name: librenms-data
  namespace: librenms
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/librenms
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librenms-data-claim
  namespace: librenms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi