# Master Poller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-poller-master
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms-poller-master
  template:
    metadata:
      labels:
        app: librenms-poller-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: server-docker
      # Master Poller
      containers:
      - name: poller
        image: librenms/librenms:latest
        command: ["/bin/sh", "-c"]
        args: 
          - |
            cd /opt/librenms
            php artisan migrate --force
            while true; do
              php artisan poller:poll -h all
              sleep 300
            done
        env:
        - name: DB_HOST
          value: "librenms-db-master"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "librenms"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: db_password
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        - name: DISPATCHER_NODE_ID
          value: "master"
        - name: POLLER_ID
          value: "1"
        - name: POLLER_THREADS
          value: "16"
        - name: POLLER_NAME
          value: "master"
        - name: DISTRIBUTED_POLLER
          value: "1"
        - name: DISTRIBUTED_POLLER_NAME
          value: "master"
        - name: DISTRIBUTED_POLLER_GROUP
          value: "0"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: app_key
        - name: APP_URL
          value: "http://librenms"
        - name: LIBRENMS_BASE
          value: "/opt/librenms"
        - name: NODE_ID
          value: "1"
        - name: POLLERS_ENABLED
          value: "true"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data-claim-master

---
# Axion Poller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-poller-axion
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms-poller-axion
  template:
    metadata:
      labels:
        app: librenms-poller-axion
    spec:
      nodeSelector:
        kubernetes.io/hostname: docker-server-axion
      containers:
      - name: poller
        image: librenms/librenms:latest
        command: ["/bin/sh", "-c"]
        args: 
          - |
            cd /opt/librenms
            php artisan migrate --force
            while true; do
              php artisan poller:poll -h all
              sleep 300
            done
        env:
        - name: DB_HOST
          value: "librenms-db-axion"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "librenms"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: db_password
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        - name: DISPATCHER_NODE_ID
          value: "axion"
        - name: POLLER_ID
          value: "2"
        - name: POLLER_THREADS
          value: "16"
        - name: POLLER_NAME
          value: "axion"
        - name: DISTRIBUTED_POLLER
          value: "1"
        - name: DISTRIBUTED_POLLER_NAME
          value: "axion"
        - name: DISTRIBUTED_POLLER_GROUP
          value: "0"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: app_key
        - name: APP_URL
          value: "http://librenms"
        - name: LIBRENMS_BASE
          value: "/opt/librenms"
        - name: NODE_ID
          value: "2"
        - name: POLLERS_ENABLED
          value: "true"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data-claim-axion

---
# Alamos Poller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-poller-alamos
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms-poller-alamos
  template:
    metadata:
      labels:
        app: librenms-poller-alamos
    spec:
      nodeSelector:
        kubernetes.io/hostname: docker-server-alamos
      containers:
      - name: poller
        image: librenms/librenms:latest
        command: ["/bin/sh", "-c"]
        args: 
          - |
            cd /opt/librenms
            php artisan migrate --force
            while true; do
              php artisan poller:poll -h all
              sleep 300
            done
        env:
        - name: DB_HOST
          value: "librenms-db-alamos"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "librenms"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: db_password
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        - name: DISPATCHER_NODE_ID
          value: "alamos"
        - name: POLLER_ID
          value: "3"
        - name: POLLER_THREADS
          value: "16"
        - name: POLLER_NAME
          value: "alamos"
        - name: DISTRIBUTED_POLLER
          value: "1"
        - name: DISTRIBUTED_POLLER_NAME
          value: "alamos"
        - name: DISTRIBUTED_POLLER_GROUP
          value: "0"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: app_key
        - name: APP_URL
          value: "http://librenms"
        - name: LIBRENMS_BASE
          value: "/opt/librenms"
        - name: NODE_ID
          value: "3"
        - name: POLLERS_ENABLED
          value: "true"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data-claim-alamos

---
# YPF Poller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-poller-ypf
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms-poller-ypf
  template:
    metadata:
      labels:
        app: librenms-poller-ypf
    spec:
      nodeSelector:
        kubernetes.io/hostname: docker-server-ypf
      containers:
      - name: poller
        image: librenms/librenms:latest
        command: ["/bin/sh", "-c"]
        args: 
          - |
            cd /opt/librenms
            php artisan migrate --force
            while true; do
              php artisan poller:poll -h all
              sleep 300
            done
        env:
        - name: DB_HOST
          value: "librenms-db-ypf"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "librenms"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: db_password
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        - name: DISPATCHER_NODE_ID
          value: "ypf"
        - name: POLLER_ID
          value: "4"
        - name: POLLER_THREADS
          value: "16"
        - name: POLLER_NAME
          value: "ypf"
        - name: DISTRIBUTED_POLLER
          value: "1"
        - name: DISTRIBUTED_POLLER_NAME
          value: "ypf"
        - name: DISTRIBUTED_POLLER_GROUP
          value: "0"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: app_key
        - name: APP_URL
          value: "http://librenms"
        - name: LIBRENMS_BASE
          value: "/opt/librenms"
        - name: NODE_ID
          value: "4"
        - name: POLLERS_ENABLED
          value: "true"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data-claim-ypf