---
- name: Install Docker on Debian servers
  hosts: all
  gather_facts: no
  vars_files:
    - .env

  tasks:
    - name: Install sudo
      raw: su -c "apt-get update && apt-get install -y sudo"
      vars:
        ansible_password: "{{ SSH_PASSWORD }}"
        ansible_become: yes
        ansible_become_method: su
        ansible_become_password: "{{ ROOT_PASSWORD }}"

    - name: Add soporte to sudoers
      raw: su -c 'echo "soporte ALL=(ALL:ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/soporte'
      vars:
        ansible_password: "{{ SSH_PASSWORD }}"
        ansible_become: yes
        ansible_become_method: su
        ansible_become_password: "{{ ROOT_PASSWORD }}"

    - name: Set correct permissions on sudoers file
      raw: chmod 0440 /etc/sudoers.d/soporte
      vars:
        ansible_become: yes
        ansible_become_method: su
        ansible_become_password: "{{ ROOT_PASSWORD }}"

    # Continue with Docker installation using sudo
    - name: Gather facts
      setup:
      become: yes
      become_method: sudo

    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: yes

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
      become: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes