---
- name: Install ArgoCD on K3s
  hosts: server1
  become: yes
  tasks:
    - name: Create argocd namespace
      shell: kubectl create namespace argocd
      ignore_errors: yes

    - name: Install ArgoCD
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Wait for ArgoCD to be ready (5 minutes max)
      shell: kubectl wait --for=condition=available --timeout=300s deployment -l "app.kubernetes.io/name=argocd-server" -n argocd

    - name: Get ArgoCD admin password
      shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password

    - name: Show ArgoCD admin password
      debug:
        msg: "ArgoCD admin password: {{ argocd_password.stdout }}"

    - name: Expose ArgoCD service
      shell: kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "NodePort"}}'