apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "America/Argentina/Buenos_Aires"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: password
            - name: PIHOLE_WEB_PORT
              value: "8888"
          ports:
            - containerPort: 53
              protocol: UDP
              hostPort: 53  # Mapea el puerto 53 en el host
            - containerPort: 53
              protocol: TCP
              hostPort: 53  # Mapea el puerto 53 en el host
            - containerPort: 8888
              protocol: TCP
      volumes:
        - name: pihole-config
          hostPath:
            path: /home/soporte/pi-hole/config
            type: DirectoryOrCreate
        - name: dnsmasq-config
          hostPath:
            path: /home/soporte/pi-hole/dnsmasq
            type: DirectoryOrCreate
