apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "America/Argentina/Buenos_Aires"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: password
            - name: PIHOLE_WEB_PORT
              value: "8080"
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
            - name: dnsmasq-config
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-config
          hostPath:
            path: pihole/config
            type: DirectoryOrCreate
        - name: dnsmasq-config
          hostPath:
            path: pihole/dnsmasq
            type: DirectoryOrCreate
