apiVersion: v1
kind: PersistentVolume
metadata:
  name: librenms-data-master
  namespace: librenms
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-docker
  hostPath:
    path: /data/librenms/master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librenms-data-claim-master
  namespace: librenms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi