apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-alamos
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms-alamos
  template:
    metadata:
      labels:
        app: librenms-alamos
    spec:
      nodeSelector:
        kubernetes.io/hostname: docker-server-alamos
      containers:
      - name: librenms
        image: librenms/librenms:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "librenms-db-alamos"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "librenms"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-secrets
              key: db_password
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data-claim-alamos
---
apiVersion: v1
kind: Service
metadata:
  name: librenms-alamos
  namespace: librenms
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30082
  selector:
    app: librenms-alamos