apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-monitor-master
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wifi-monitor-master
  template:
    metadata:
      labels:
        app: wifi-monitor-master
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: server-docker
      containers:
      - name: wifi-monitor
        image: brclucas/wifi-monitor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: wifi-monitor-master-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-monitor-axion
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wifi-monitor-axion
  template:
    metadata:
      labels:
        app: wifi-monitor-axion
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-axion
      containers:
      - name: wifi-monitor
        image: brclucas/wifi-monitor:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: wifi-monitor-axion-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-monitor-alamos
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wifi-monitor-alamos
  template:
    metadata:
      labels:
        app: wifi-monitor-alamos
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-alamos
      containers:
      - name: wifi-monitor
        image: brclucas/wifi-monitor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: wifi-monitor-alamos-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-monitor-ypf
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wifi-monitor-ypf
  template:
    metadata:
      labels:
        app: wifi-monitor-ypf
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: docker-server-ypf
      containers:
      - name: wifi-monitor
        image: brclucas/wifi-monitor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: wifi-monitor-ypf-secrets