apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-proxy
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: myapp
data:
  default.conf: |
    server {
        listen 8080;
        server_name server-docker;
        location / {
            proxy_pass http://10.43.233.249:80;  # Using ClusterIP of hello-world-master
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 10;
            proxy_send_timeout 30;
            proxy_read_timeout 30;
        }
    }
    server {
        listen 8080;
        server_name docker-server-axion;
        location / {
            proxy_pass http://10.43.34.73:80;  # Using ClusterIP of hello-world-axion
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 8080;
        server_name docker-server-alamos;
        location / {
            proxy_pass http://10.43.241.118:80;  # Using ClusterIP of hello-world-alamos
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    server {
        listen 8080;
        server_name docker-server-ypf;
        location / {
            proxy_pass http://10.43.69.192:80;  # Using ClusterIP of hello-world-ypf
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }