apiVersion: v1
kind: Service
metadata:
  name: hello-world-master
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: hello-world
    kubernetes.io/hostname: server-docker

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-axion
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-axion

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-alamos
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-alamos

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-ypf
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-ypf
apiVersion: v1
kind: Service
metadata:
  name: hello-world-master
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: hello-world
    kubernetes.io/hostname: server-docker