apiVersion: v1
kind: Service
metadata:
  name: wifi-monitor-master
  namespace: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: wifi-monitor-master

---
apiVersion: v1
kind: Service
metadata:
  name: wifi-monitor-axion
  namespace: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: wifi-monitor-axion

---
apiVersion: v1
kind: Service
metadata:
  name: wifi-monitor-alamos
  namespace: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: wifi-monitor-alamos

---
apiVersion: v1
kind: Service
metadata:
  name: wifi-monitor-ypf
  namespace: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: wifi-monitor-ypf
