apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: sic-cluster
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: hello-world