apiVersion: v1
kind: Service
metadata:
  name: hello-world-master
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-axion
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-axion

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-alamos
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-alamos

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-ypf
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
    kubernetes.io/hostname: docker-server-ypf
